nota1 = int(input("Digite a primeira nota: "))
nota2 = int(input("Digite a segunda nota: "))
nota3 = int(input("Digite a tercerira nota: "))
media = ((nota1 + nota2 + nota3) / 3)
print ("A média das notas " , nota1 , " , " , nota2 , " e " , nota3 , " é " , media)